import FWCore.ParameterSet.Config as cms

hltParticleNetJetTagInfos = cms.EDProducer( "DeepBoostedJetTagInfoProducer",
    jet_radius = cms.double( 0.4 ),
    min_jet_pt = cms.double( 30.0 ),
    max_jet_eta = cms.double( 2.5 ),
    min_pt_for_track_properties = cms.double( 0.95 ),
    min_pt_for_pfcandidates = cms.double( 0.1 ),
    use_puppiP4 = cms.bool( False ),
    include_neutrals = cms.bool( True ),
    sort_by_sip2dsig = cms.bool( False ),
    min_puppi_wgt = cms.double( -1.0 ),
    flip_ip_sign = cms.bool( False ),
    sip3dSigMax = cms.double( -1.0 ),
    use_hlt_features = cms.bool( True ),
    vertices = cms.InputTag( "hltPhase2PixelVertices" ),
    secondary_vertices = cms.InputTag( "hltDeepInclusiveMergedVerticesPF" ),
    pf_candidates = cms.InputTag( "particleFlowTmp" ),
    jets = cms.InputTag( "hltPFJetForBtag" ),
    puppi_value_map = cms.InputTag( "" ),
    vertex_associator = cms.InputTag( 'hltPrimaryVertexAssociation','original' ),
    use_scouting_features = cms.bool( False ),
    normchi2_value_map = cms.InputTag( "" ),
    dz_value_map = cms.InputTag( "" ),
    dxy_value_map = cms.InputTag( "" ),
    dzsig_value_map = cms.InputTag( "" ),
    dxysig_value_map = cms.InputTag( "" ),
    lostInnerHits_value_map = cms.InputTag( "" ),
    quality_value_map = cms.InputTag( "" ),
    trkPt_value_map = cms.InputTag( "" ),
    trkEta_value_map = cms.InputTag( "" ),
    trkPhi_value_map = cms.InputTag( "" )
)